with Ada.Text_IO;
with Q_FP_DATA;
with Q_FP_DATA.Q_MANAGER;

procedure M_FPL_EXERCISE is

   function F_CREATE_FLIGHT_PLAN
     (V_CALLSIGN : Q_FP_DATA.T_CALLSIGN; V_SSR : Q_FP_DATA.T_SSR) return Q_FP_DATA.T_FLIGHT_PLAN
   is
      V_TEMP_FPL : Q_FP_DATA.T_FLIGHT_PLAN;
   begin
      if V_CALLSIGN'LENGTH > 7 then
         Ada.Text_IO.Put_Line
           ("Callsign too long. Maximum LENGTH is 7 characters.");
         return V_TEMP_FPL;
      end if;
      -- Example of adding a flight plan
      V_TEMP_FPL.R_CALLSIGN := Q_FP_DATA.C_EMPTY_CALLSIGN;
      V_TEMP_FPL.R_CALLSIGN (1 .. V_CALLSIGN'LENGTH) := V_CALLSIGN;
      V_TEMP_FPL.R_ADEP := "EGLL";
      V_TEMP_FPL.R_ADES := "EGKK";
      V_TEMP_FPL.R_EOBT := "1200";
      V_TEMP_FPL.R_EOBD := "230101";
      V_TEMP_FPL.R_FLIGHT_RULE := 'I';
      V_TEMP_FPL.R_FLIGHT_TYPE := 'S';
      V_TEMP_FPL.R_AIRCRAFT_NUMBER := "01";
      V_TEMP_FPL.R_AIRCRAFT_TYPE := "A320";
      V_TEMP_FPL.R_WAKE_TURBULENCE := 'M';
      V_TEMP_FPL.R_NCA_EQUIPMENT (1 .. 3) := "N/A";
      V_TEMP_FPL.R_SSR_EQUIPMENT (1 .. 3) := "N/A";
      V_TEMP_FPL.R_SSR_CODE := V_SSR;
      V_TEMP_FPL.R_TAS (1 .. 4) := "250K";
      V_TEMP_FPL.R_RFL := "FL350";
      V_TEMP_FPL.R_ROUTE (1 .. 21) := "EGLL ACORN XAMAN EGKK";
      return V_TEMP_FPL;
   end F_CREATE_FLIGHT_PLAN;
begin
   Q_FP_DATA.Q_MANAGER.P_ADD_FLIGHT_PLAN (F_CREATE_FLIGHT_PLAN (V_CALLSIGN => "ABC1234", V_SSR => "1234"));
   Q_FP_DATA.Q_MANAGER.P_ADD_FLIGHT_PLAN (F_CREATE_FLIGHT_PLAN (V_CALLSIGN => "XYZ4567", V_SSR => "7600"));
   Q_FP_DATA.Q_MANAGER.P_ADD_FLIGHT_PLAN (F_CREATE_FLIGHT_PLAN (V_CALLSIGN => "LMN7890", V_SSR => "5467"));
   Q_FP_DATA.Q_MANAGER.P_ADD_FLIGHT_PLAN (F_CREATE_FLIGHT_PLAN (V_CALLSIGN => "DEF0123", V_SSR => "3643"));
   Q_FP_DATA.Q_MANAGER.P_ADD_FLIGHT_PLAN (F_CREATE_FLIGHT_PLAN (V_CALLSIGN => "GHI3456", V_SSR => "7700"));

   Q_FP_DATA.Q_MANAGER.P_DELETE_FLIGHT_PLAN (V_INDEX => 0);
   Q_FP_DATA.Q_MANAGER.P_DELETE_FLIGHT_PLAN (V_CALLSIGN => "XYZ4567");
   Q_FP_DATA.Q_MANAGER.P_DELETE_FLIGHT_PLAN
     (V_INDEX => 1, V_CALLSIGN => "GHI3456");

   Ada.Text_IO.Put_Line ("Unsorted Flight Plans:");
   Q_FP_DATA.Q_MANAGER.P_DISPLAY_FLIGHT_PLANS;
   Q_FP_DATA.Q_MANAGER.P_SORT_FLIGHT_PLANS
     (V_CRITERION => Q_FP_DATA.Q_MANAGER.E_CALLSIGN);
   Ada.Text_IO.Put_Line ("Flight Plans Sorted by Callsign:");
   Q_FP_DATA.Q_MANAGER.P_DISPLAY_FLIGHT_PLANS;

   Q_FP_DATA.Q_MANAGER.P_SORT_FLIGHT_PLANS
     (V_CRITERION => Q_FP_DATA.Q_MANAGER.E_SSR_CODE);
   Ada.Text_IO.Put_Line ("Flight Plans Sorted by SSR:");
   Q_FP_DATA.Q_MANAGER.P_DISPLAY_FLIGHT_PLANS;

end M_FPL_EXERCISE;
